/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./mail.gltf 
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mail-icon-b9133b28050d43aeb973aa0f08f86441
Title: Mail Icon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mail.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} scale={50} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} scale={50} />
      </group>
    </group>
  )
}

useGLTF.preload('/mail.gltf')
